defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"
    meurio_accounts:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "postgresql"
          host: "localhost"
          username: "josias"
          password: "josias"
          database: "meurio_accounts_development"
        table: "users"
        username_column: "email"
        password_column: "encrypted_password"

test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production:
  <<: *defaults
  frontend:
    sso_name: 'CASino'
    footer_text: 'Powered by <a href="http://rbcas.com/">CASino</a>'
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"
    meurio_accounts:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "postgresql"
          host: <%= ENV['MEURIO_ACCOUNTS_DBHOST'] %>
          username: <%= ENV['MEURIO_ACCOUNTS_DBNAME'] %>
          password: <%= ENV['MEURIO_ACCOUNTS_DBPASS'] %>
          database: <%= ENV['MEURIO_ACCOUNTS_DBUSER'] %>
        table: "users"
        username_column: "email"
        password_column: "encrypted_password"
